### ISSUE TITLE
Automatisiert ausführen

### ISSUE THREAD

**Issue by mojoaxel** [FreifunkFranken/community.franken.freifunk.net#1]
Bisher wird das Update mauel ausgeführt. Es sollte auf einem geeigneten Server z.B. ein Cron-Job angelegt werden, der die Communities z.B. jede Stunde updated.

**Comment by kratz00** [comment]
Kann ich uebernehmen, braeuchte dafuer aber commit Rechte auf https://github.com/FreifunkFranken/freifunkfranken-community

**Comment by kratz00** [comment]
@mojoaxel Danke fuer die Schreibrechte.
- Ich habe nichts gefunden, weisst du wie oft (in welchem Intervall) die Community Dateien abgerufen werden?

Hintergrund: Es wuerde nicht viel Sinn machen, wenn wir die Community Dateien alle Stunde erzeugen, diese aber nur zwei mal am Tag abgerufen werden wuerden.

**Comment by mojoaxel** [comment]
Ich glaube die Daten für freifunk.net werden alle 15 Minuten abgerufen. Eine Aktualisierung alle 6 Stunden ist auf unserer Seite aber sicherlich ausreichen, da der Abruf den Netmon zusätzlich belastet und sich die Knotenanzahl ja nur selten ändert.

**Comment by kratz00** [comment]
Ich aktualisiere jetzt alle 6 Stunden die Community-Dateien ueber mein NAS.
Das einzige Problem was ich aktuell sehe ist wenn jemand anderes auch die Dateien aktualisiert und einchecked. Es gibt dann ein kurzes Zeitfenster zwischen 'git pull', erzeugen und 'git push' der Community-Dateien, wo die Sache schief gehen kann. Die Wahrscheinlichkeit sehe ich aber eher gering.

**Comment by mojoaxel** [comment]
@kratz00 Schön, dass es jetzt läuft!

Könntest du evtl. ein paar Worte zum cronjob/Rechtevergabe im Readme ergänzen, damit auch andere das laufen lassen können.

Jetzt sollten wir mal mit magenbrot sprechen, damit wir das Ding auf dem neuen netmon-server laufen lassen können. Da ist es meiner meinung nach am besten aufgehoben.

**Comment by kratz00** [comment]
Lief natuerlich nicht in der Nacht :(
Ich schreibe da gerne was dazu, aber erst nach dem Urlaub :)
Mal gucken ob es waehrend des Urlaubs verlaesslich laeuft.

**Comment by mojoaxel** [comment]
Ich bin ehrlich gesagt etwas erleichtert, dass ich nicht der einzige bin, der mit dem Ding Probleme hat :-)

**Comment by kratz00** [comment]
Mein Problem hatte nicht mit Cron zu tun.
Auf der Kiste, wo der Job aktuell laeuft, muss man das Web-Interface des "Task Schedulers" verwenden, um cron daemon Funktionalitaet  nutzen zu koennen.
Ich habe jetzt verstanden wie es funktioniert und die Community-Dateien werden alle 6 Stunden aktualisiert.

**Comment by mojoaxel** [comment]
Ich würde das gern auf den netmon server laufen lassen. Das ist wahrscheinlich ein "normales" Debian. Gibts da noch irgendwas zu beachten?

**Comment by kratz00** [comment]
Wuesste spontan nichts.

Als normaler User (uid != 0) einfach:

```
crontab -e
0 0,6,12,18 * * * /path/to/updateFromNetmon.sh
```

Und dann werden wie jetzt auch, die Community-Dateien immer um 0, 6, 12 und 18 Uhr aktualisiert.

**Comment by mojoaxel** [comment]
OK. Thx
