### ISSUE TITLE
Verbesserung: Schluessel sortieren

### ISSUE THREAD

**Issue by kratz00** [FreifunkFranken/community.franken.freifunk.net#6]
Da auf meinem NAS kein Node.js zur Verfuegung steht (und sich dies nicht trivial aendern laesst) habe ich eine eigene Loesung in Python. Da die Programmiersprache keine Rolle spielen sollte wuerde ich gerne die Ausgabe mehr standardisieren, um den Diff bei Commits zu minimieren (z.B.:https://github.com/FreifunkFranken/freifunkfranken-community/commit/2d5fccf929a31fd05a19fd61458898878f69623d ). Ausser dem Datum und der Node Anzahl sollte sich normal nichts aendern.
- 4 Spaces zum Einruecken
- Schluessel alphabetisch sortieren

**Comment by mojoaxel** [comment]
Gute Idee!
Die 4 Spaces sind aber doch schon drin...
Das Sortieren der Felder bau ich in die node-version ein.

**Comment by kratz00** [comment]
@ 4 Spaces
Stimmt, wollte es nur der Uebersicht halber mit auffuehren.

Das eigentliche To-Do liegt beim Sortieren der Schluessel, deswegen auch dieses Ticket.
