### ISSUE TITLE
Community Feucht mit aufnehmen.

### ISSUE THREAD

**Issue by mojoaxel** [FreifunkFranken/community.franken.freifunk.net#8]
Es wurde der Wunsch ausgesprochen eine Community "Feucht" mit in Franken-Netz aufzunehmen. 
Siehe https://github.com/freifunk/directory.api.freifunk.net/pull/258

**Comment by mojoaxel** [comment]
Vorlage: https://tretkowski.de/Freifunk/api.json

**Comment by kratz00** [comment]
Wie ist hier der aktuelle Stand?

**Comment by mojoaxel** [comment]
@nobse Wie schauts aus?
